// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notification/ent/message"
	"notification/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetType sets the "type" field.
func (mu *MessageUpdate) SetType(s string) *MessageUpdate {
	mu.mutation.SetType(s)
	return mu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableType(s *string) *MessageUpdate {
	if s != nil {
		mu.SetType(*s)
	}
	return mu
}

// SetPayload sets the "payload" field.
func (mu *MessageUpdate) SetPayload(m map[string]interface{}) *MessageUpdate {
	mu.mutation.SetPayload(m)
	return mu
}

// SetStatus sets the "status" field.
func (mu *MessageUpdate) SetStatus(m message.Status) *MessageUpdate {
	mu.mutation.SetStatus(m)
	return mu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableStatus(m *message.Status) *MessageUpdate {
	if m != nil {
		mu.SetStatus(*m)
	}
	return mu
}

// SetAttempts sets the "attempts" field.
func (mu *MessageUpdate) SetAttempts(i int) *MessageUpdate {
	mu.mutation.ResetAttempts()
	mu.mutation.SetAttempts(i)
	return mu
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableAttempts(i *int) *MessageUpdate {
	if i != nil {
		mu.SetAttempts(*i)
	}
	return mu
}

// AddAttempts adds i to the "attempts" field.
func (mu *MessageUpdate) AddAttempts(i int) *MessageUpdate {
	mu.mutation.AddAttempts(i)
	return mu
}

// SetNextRetryAt sets the "next_retry_at" field.
func (mu *MessageUpdate) SetNextRetryAt(t time.Time) *MessageUpdate {
	mu.mutation.SetNextRetryAt(t)
	return mu
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableNextRetryAt(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetNextRetryAt(*t)
	}
	return mu
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (mu *MessageUpdate) ClearNextRetryAt() *MessageUpdate {
	mu.mutation.ClearNextRetryAt()
	return mu
}

// SetCreatedAt sets the "created_at" field.
func (mu *MessageUpdate) SetCreatedAt(t time.Time) *MessageUpdate {
	mu.mutation.SetCreatedAt(t)
	return mu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableCreatedAt(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetCreatedAt(*t)
	}
	return mu
}

// SetUpdatedAt sets the "updated_at" field.
func (mu *MessageUpdate) SetUpdatedAt(t time.Time) *MessageUpdate {
	mu.mutation.SetUpdatedAt(t)
	return mu
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	mu.defaults()
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mu *MessageUpdate) defaults() {
	if _, ok := mu.mutation.UpdatedAt(); !ok {
		v := message.UpdateDefaultUpdatedAt()
		mu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MessageUpdate) check() error {
	if v, ok := mu.mutation.GetType(); ok {
		if err := message.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Message.type": %w`, err)}
		}
	}
	if v, ok := mu.mutation.Status(); ok {
		if err := message.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Message.status": %w`, err)}
		}
	}
	return nil
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.GetType(); ok {
		_spec.SetField(message.FieldType, field.TypeString, value)
	}
	if value, ok := mu.mutation.Payload(); ok {
		_spec.SetField(message.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := mu.mutation.Status(); ok {
		_spec.SetField(message.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := mu.mutation.Attempts(); ok {
		_spec.SetField(message.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := mu.mutation.AddedAttempts(); ok {
		_spec.AddField(message.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := mu.mutation.NextRetryAt(); ok {
		_spec.SetField(message.FieldNextRetryAt, field.TypeTime, value)
	}
	if mu.mutation.NextRetryAtCleared() {
		_spec.ClearField(message.FieldNextRetryAt, field.TypeTime)
	}
	if value, ok := mu.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := mu.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetType sets the "type" field.
func (muo *MessageUpdateOne) SetType(s string) *MessageUpdateOne {
	muo.mutation.SetType(s)
	return muo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableType(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetType(*s)
	}
	return muo
}

// SetPayload sets the "payload" field.
func (muo *MessageUpdateOne) SetPayload(m map[string]interface{}) *MessageUpdateOne {
	muo.mutation.SetPayload(m)
	return muo
}

// SetStatus sets the "status" field.
func (muo *MessageUpdateOne) SetStatus(m message.Status) *MessageUpdateOne {
	muo.mutation.SetStatus(m)
	return muo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableStatus(m *message.Status) *MessageUpdateOne {
	if m != nil {
		muo.SetStatus(*m)
	}
	return muo
}

// SetAttempts sets the "attempts" field.
func (muo *MessageUpdateOne) SetAttempts(i int) *MessageUpdateOne {
	muo.mutation.ResetAttempts()
	muo.mutation.SetAttempts(i)
	return muo
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableAttempts(i *int) *MessageUpdateOne {
	if i != nil {
		muo.SetAttempts(*i)
	}
	return muo
}

// AddAttempts adds i to the "attempts" field.
func (muo *MessageUpdateOne) AddAttempts(i int) *MessageUpdateOne {
	muo.mutation.AddAttempts(i)
	return muo
}

// SetNextRetryAt sets the "next_retry_at" field.
func (muo *MessageUpdateOne) SetNextRetryAt(t time.Time) *MessageUpdateOne {
	muo.mutation.SetNextRetryAt(t)
	return muo
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableNextRetryAt(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetNextRetryAt(*t)
	}
	return muo
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (muo *MessageUpdateOne) ClearNextRetryAt() *MessageUpdateOne {
	muo.mutation.ClearNextRetryAt()
	return muo
}

// SetCreatedAt sets the "created_at" field.
func (muo *MessageUpdateOne) SetCreatedAt(t time.Time) *MessageUpdateOne {
	muo.mutation.SetCreatedAt(t)
	return muo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableCreatedAt(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetCreatedAt(*t)
	}
	return muo
}

// SetUpdatedAt sets the "updated_at" field.
func (muo *MessageUpdateOne) SetUpdatedAt(t time.Time) *MessageUpdateOne {
	muo.mutation.SetUpdatedAt(t)
	return muo
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (muo *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	muo.defaults()
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (muo *MessageUpdateOne) defaults() {
	if _, ok := muo.mutation.UpdatedAt(); !ok {
		v := message.UpdateDefaultUpdatedAt()
		muo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MessageUpdateOne) check() error {
	if v, ok := muo.mutation.GetType(); ok {
		if err := message.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Message.type": %w`, err)}
		}
	}
	if v, ok := muo.mutation.Status(); ok {
		if err := message.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Message.status": %w`, err)}
		}
	}
	return nil
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.GetType(); ok {
		_spec.SetField(message.FieldType, field.TypeString, value)
	}
	if value, ok := muo.mutation.Payload(); ok {
		_spec.SetField(message.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := muo.mutation.Status(); ok {
		_spec.SetField(message.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := muo.mutation.Attempts(); ok {
		_spec.SetField(message.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := muo.mutation.AddedAttempts(); ok {
		_spec.AddField(message.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := muo.mutation.NextRetryAt(); ok {
		_spec.SetField(message.FieldNextRetryAt, field.TypeTime, value)
	}
	if muo.mutation.NextRetryAtCleared() {
		_spec.ClearField(message.FieldNextRetryAt, field.TypeTime)
	}
	if value, ok := muo.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := muo.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
