// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notification/ent/message"
	"notification/ent/retry"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RetryCreate is the builder for creating a Retry entity.
type RetryCreate struct {
	config
	mutation *RetryMutation
	hooks    []Hook
}

// SetMessageUUID sets the "message_uuid" field.
func (rc *RetryCreate) SetMessageUUID(u uuid.UUID) *RetryCreate {
	rc.mutation.SetMessageUUID(u)
	return rc
}

// SetStatus sets the "status" field.
func (rc *RetryCreate) SetStatus(r retry.Status) *RetryCreate {
	rc.mutation.SetStatus(r)
	return rc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rc *RetryCreate) SetNillableStatus(r *retry.Status) *RetryCreate {
	if r != nil {
		rc.SetStatus(*r)
	}
	return rc
}

// SetAttempts sets the "attempts" field.
func (rc *RetryCreate) SetAttempts(i int) *RetryCreate {
	rc.mutation.SetAttempts(i)
	return rc
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (rc *RetryCreate) SetNillableAttempts(i *int) *RetryCreate {
	if i != nil {
		rc.SetAttempts(*i)
	}
	return rc
}

// SetNextRetryAt sets the "next_retry_at" field.
func (rc *RetryCreate) SetNextRetryAt(t time.Time) *RetryCreate {
	rc.mutation.SetNextRetryAt(t)
	return rc
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (rc *RetryCreate) SetNillableNextRetryAt(t *time.Time) *RetryCreate {
	if t != nil {
		rc.SetNextRetryAt(*t)
	}
	return rc
}

// SetCreatedAt sets the "created_at" field.
func (rc *RetryCreate) SetCreatedAt(t time.Time) *RetryCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *RetryCreate) SetNillableCreatedAt(t *time.Time) *RetryCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetUpdatedAt sets the "updated_at" field.
func (rc *RetryCreate) SetUpdatedAt(t time.Time) *RetryCreate {
	rc.mutation.SetUpdatedAt(t)
	return rc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rc *RetryCreate) SetNillableUpdatedAt(t *time.Time) *RetryCreate {
	if t != nil {
		rc.SetUpdatedAt(*t)
	}
	return rc
}

// SetMessageID sets the "message" edge to the Message entity by ID.
func (rc *RetryCreate) SetMessageID(id uuid.UUID) *RetryCreate {
	rc.mutation.SetMessageID(id)
	return rc
}

// SetMessage sets the "message" edge to the Message entity.
func (rc *RetryCreate) SetMessage(m *Message) *RetryCreate {
	return rc.SetMessageID(m.ID)
}

// Mutation returns the RetryMutation object of the builder.
func (rc *RetryCreate) Mutation() *RetryMutation {
	return rc.mutation
}

// Save creates the Retry in the database.
func (rc *RetryCreate) Save(ctx context.Context) (*Retry, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RetryCreate) SaveX(ctx context.Context) *Retry {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RetryCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RetryCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RetryCreate) defaults() {
	if _, ok := rc.mutation.Status(); !ok {
		v := retry.DefaultStatus
		rc.mutation.SetStatus(v)
	}
	if _, ok := rc.mutation.Attempts(); !ok {
		v := retry.DefaultAttempts
		rc.mutation.SetAttempts(v)
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := retry.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		v := retry.DefaultUpdatedAt()
		rc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RetryCreate) check() error {
	if _, ok := rc.mutation.MessageUUID(); !ok {
		return &ValidationError{Name: "message_uuid", err: errors.New(`ent: missing required field "Retry.message_uuid"`)}
	}
	if _, ok := rc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Retry.status"`)}
	}
	if v, ok := rc.mutation.Status(); ok {
		if err := retry.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Retry.status": %w`, err)}
		}
	}
	if _, ok := rc.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "Retry.attempts"`)}
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Retry.created_at"`)}
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Retry.updated_at"`)}
	}
	if len(rc.mutation.MessageIDs()) == 0 {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required edge "Retry.message"`)}
	}
	return nil
}

func (rc *RetryCreate) sqlSave(ctx context.Context) (*Retry, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RetryCreate) createSpec() (*Retry, *sqlgraph.CreateSpec) {
	var (
		_node = &Retry{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(retry.Table, sqlgraph.NewFieldSpec(retry.FieldID, field.TypeInt))
	)
	if value, ok := rc.mutation.Status(); ok {
		_spec.SetField(retry.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := rc.mutation.Attempts(); ok {
		_spec.SetField(retry.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := rc.mutation.NextRetryAt(); ok {
		_spec.SetField(retry.FieldNextRetryAt, field.TypeTime, value)
		_node.NextRetryAt = &value
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.SetField(retry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.UpdatedAt(); ok {
		_spec.SetField(retry.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := rc.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   retry.MessageTable,
			Columns: []string{retry.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageUUID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RetryCreateBulk is the builder for creating many Retry entities in bulk.
type RetryCreateBulk struct {
	config
	err      error
	builders []*RetryCreate
}

// Save creates the Retry entities in the database.
func (rcb *RetryCreateBulk) Save(ctx context.Context) ([]*Retry, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Retry, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RetryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RetryCreateBulk) SaveX(ctx context.Context) []*Retry {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RetryCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RetryCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
