// Code generated by ent, DO NOT EDIT.

package ent

import (
	"notification/ent/message"
	"notification/ent/retry"
	"notification/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescType is the schema descriptor for type field.
	messageDescType := messageFields[1].Descriptor()
	// message.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	message.TypeValidator = messageDescType.Validators[0].(func(string) error)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[4].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescUpdatedAt is the schema descriptor for updated_at field.
	messageDescUpdatedAt := messageFields[5].Descriptor()
	// message.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	message.DefaultUpdatedAt = messageDescUpdatedAt.Default.(func() time.Time)
	// message.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	message.UpdateDefaultUpdatedAt = messageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
	retryFields := schema.Retry{}.Fields()
	_ = retryFields
	// retryDescAttempts is the schema descriptor for attempts field.
	retryDescAttempts := retryFields[2].Descriptor()
	// retry.DefaultAttempts holds the default value on creation for the attempts field.
	retry.DefaultAttempts = retryDescAttempts.Default.(int)
	// retryDescCreatedAt is the schema descriptor for created_at field.
	retryDescCreatedAt := retryFields[4].Descriptor()
	// retry.DefaultCreatedAt holds the default value on creation for the created_at field.
	retry.DefaultCreatedAt = retryDescCreatedAt.Default.(func() time.Time)
	// retryDescUpdatedAt is the schema descriptor for updated_at field.
	retryDescUpdatedAt := retryFields[5].Descriptor()
	// retry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	retry.DefaultUpdatedAt = retryDescUpdatedAt.Default.(func() time.Time)
	// retry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	retry.UpdateDefaultUpdatedAt = retryDescUpdatedAt.UpdateDefault.(func() time.Time)
}
