// Code generated by ent, DO NOT EDIT.

package ent

import (
	"notification/ent/message"
	"notification/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescType is the schema descriptor for type field.
	messageDescType := messageFields[1].Descriptor()
	// message.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	message.TypeValidator = messageDescType.Validators[0].(func(string) error)
	// messageDescAttempts is the schema descriptor for attempts field.
	messageDescAttempts := messageFields[4].Descriptor()
	// message.DefaultAttempts holds the default value on creation for the attempts field.
	message.DefaultAttempts = messageDescAttempts.Default.(int)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[6].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescUpdatedAt is the schema descriptor for updated_at field.
	messageDescUpdatedAt := messageFields[7].Descriptor()
	// message.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	message.DefaultUpdatedAt = messageDescUpdatedAt.Default.(func() time.Time)
	// message.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	message.UpdateDefaultUpdatedAt = messageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
}
